server:
  port: 8080

spring:
  application:
    name: msvc-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true  # Importante para CloudMap
      routes:
        - id: products-service
          uri: lb://msvc-products
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1  # /api/products/** → /products/**

        - id: orders-service
          uri: lb://msvc-orders
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1

        - id: payments-service
          uri: lb://msvc-pay
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=1

        - id: users-service
          uri: lb://msvc-users
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eurekaservice.microservices-fargate.local:8761/eureka/}
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    metadata-map:
      startup: ${random.int}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always