server:
  port: 8080

spring:
  application:
    name: msvc-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: products-services
          uri: lb://msvc-products
          predicates:
            - Path=/products/**

        - id: orders-services
          uri: lb://msvc-orders
          predicates:
            - Path=/orders/**

        - id: payments-services
          uri: lb://msvc-pay
          predicates:
            - Path=/pay/**

        - id: users-services
          uri: lb://msvc-users
          predicates:
            - Path=/users/**

eureka:
  client:
    service-url:
      # En Docker: http://eureka-service:8761/eureka/
      # En ECS/CloudMap: http://eurekaservice:8761/eureka/ (según nombre)
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-service:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always