server:
  port: 8004

spring:
  application:
    name: msvc-users

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:app}?useSSL=true&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initializationFailTimeout: 0

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eurekaservice:8761/eureka/

jwt:
  secret: ${JWT_SECRET:change-me}

management:
  endpoints:
    web:
      exposure:
        include: health,info
