server:
  port: 8080

spring:
  application:
    name: msvc-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: products-services
          uri: lb://msvc-products
          predicates:
            - Path=/products/**
          filters:
            - AuthFilter

        - id: orders-services
          uri: lb://msvc-orders
          predicates:
            - Path=/orders/**
          filters:
            - AuthFilter

        - id: payments-services
          uri: lb://msvc-pay
          predicates:
            - Path=/pay/**
          filters:
            - AuthFilter

        - id: users-services
          uri: lb://msvc-users
          predicates:
            - Path=/users/**

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${HOSTNAME:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      # ✅ Recomendado: setear EUREKA_URL desde ECS:
      #    EUREKA_URL=http://eurekaservice.microservices-fargate-demo.local:8761
      # Si no existe, usa el FQDN de Cloud Map como fallback:
      defaultZone: ${EUREKA_URL:http://eurekaservice.microservices-fargate-demo.local:8761}/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always