server:
  port: ${SERVER_PORT:8761}  # Toma de variable de entorno, default 8761

spring:
  application:
    name: msvc-eureka

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_INSTANCE_HOSTNAME:eurekaservice}  # Importante para DNS

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always